plugins {
	id "net.fabricmc.fabric-loom" version "${loom_version}"
}

version = "${project.mod_version}+mc${project.minecraft_version}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven {
		name = "Terraformers"
		url = "https://maven.terraformersmc.com/releases/"
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"${project.mod_id}" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	compileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
	localRuntime "com.terraformersmc:modmenu:${project.modmenu_version}"
}

def resourceProperties = [
	"version": project.version,
	"mod_id": project.mod_id,
	"mod_name": project.mod_name,
	"minecraft_version": project.minecraft_version
]

processResources {
	inputs.properties resourceProperties
	filesMatching("fabric.mod.json") {
		expand resourceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = Integer.parseInt(project.java_version)
	options.encoding = "UTF-8"
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.toVersion(project.java_version)
	targetCompatibility = JavaVersion.toVersion(project.java_version)
}
